### ISSUE TITLE
bug in finalize() when using unittest.TestCase classes

### ISSUE THREAD

**Issue by AlbertDeFusco** [datacamp/ipython_nose#6]
@machow 

The [_dump_test function() on line 75](https://github.com/datacamp/ipython_nose/blob/6e2c9e0f0cedcb55eb01721e1b4721e162d62cd7/ipython_nose.py#L75) throws an `AttributeError` error when I try to use `unittest.TestCase` classes. Test classes that are not subclasses of `unittest.TestCase` do not work with `ipython_nose`.

```python
%%nose
import itertools, io
import unittest

class ValidationTests(unittest.TestCase):
    def setUp(self):
        pw = itertools.cycle(b'datacamp')
        validation_crypt = open('datasets/wine_validation.csv.encrypted', 'rb').read()
        decrypted = bytes(a^b for (a, b) in zip(pw, validation_crypt))
        validation = pd.read_csv(io.StringIO(decrypted.decode('ascii')), index_col=0)
        self.X_valid = validation.drop('quality', axis='columns').values.copy()
        self.y_valid = validation['quality'].map({'bad':0, 'good':1}).values

    def test_model_score(self):
        score = model.score(self.X_valid, self.y_valid)
        assert score > 0.65, \
            "You have not found a model with 65% accuracy"
```

```python
~/Applications/miniconda3/envs/proj_ml1/lib/python3.6/site-packages/ipython_nose.py in finalize(self, result)
    186                 result.wasSuccessful(),
    187                 self.num_tests, self.n_failures, self.n_errors,
--> 188                 self.tests)
    189 
    190     def setOutputStream(self, stream):

~/Applications/miniconda3/envs/proj_ml1/lib/python3.6/site-packages/ipython_nose.py in finalize(self, pass_or_fail, n_tests, n_failures, n_errors, tests)
     58                    "errors":   n_errors      # The number of tests that errored out, which mean it couldn't run but dind'
     59                    },
---> 60                "tests": list(map(self._dump_test, tests))
     61                }
     62 

~/Applications/miniconda3/envs/proj_ml1/lib/python3.6/site-packages/ipython_nose.py in _dump_test(self, test_tuple)
     73     def _dump_test(self, test_tuple):
     74         test, exc, res  = test_tuple
---> 75         return { "name": str(test.test.test.__name__), # NoseTest.SomeTestCaseClass.func
     76                  "success": res == "success",
     77                  "message": ''.join(traceback.format_exception(*exc)[-1:]) if res != "success" else ""}

AttributeError: 'ContextSuite' object has no attribute 'test'
```

**Comment by machow** [comment]
@AlbertDeFusco thanks for raising this. I'll have to look into how nose runs unittest.TestCase. However, I want to be sure I understand the other issue you mention..

> Test classes that are not subclasses of unittest.TestCase do not work with ipython_nose.

I just tested, and it seems to work. Can you test with a class of the form below? ipython_nose uses nose's standard test matching rules, and I'm not sure whether they'd match the name `ValidationTests`.

```
%%nose

class TestB():
    def test_a(self):
        
        assert a == 2, 'a is not 2'
```

**Comment by AlbertDeFusco** [comment]
Ah, I see. I had not named my classes `Test.*`

**Comment by AlbertDeFusco** [comment]
Now I've noticed that generators do not fail correctly for *unexpected errors* using the DataCamp ipython_nose.

See https://github.com/datacamp/certification-machine-learning-project-2/issues/3 for related content.

Here's a simple test case. The test taker was asked to create a NumPy array of ints (or some object that has a `dtype` attribute. Instead a `list` was created. In the test function the line `d = ints.dtype` will fail with an AttributeError before getting to the assertion.

```python
In [1]: %load_ext ipython_nose                                                                                               
                                                      
In [2]: import numpy as np               
                                                                                                                       
In [3]: ints = np.random.randint(0, 10, size=5).tolist()
                                                                                                                    
In [4]: ints                                 
Out[4]: [8, 1, 1, 6, 2]   
```


## Correct failure case
This test function fails because `ints.dtype` does not exist and to me is a valid failure mode. The test-taker did not follow the directions carefully that `ints` must be a NumPy array.
                       
```python                                                                                     
In [5]: %%nose                                       
   ...: def test_values():                                                                                   
   ...:     d = ints.dtype                                        
   ...:     assert (ints > 5).all(), 'All values are not greater than 5'                                                                                                          
Out[5]:                             
0/1 tests passed; 1 failed                                       
========                                                                    
__main__.test_values                                                       
========                                                                                                                                                 
Traceback (most recent call last):                                                                                                                                                
  File "/Users/adefusco/Applications/miniconda3/envs/dc_tests/lib/python3.6/unittest/case.py", line 59, in testPartExecutor
    yield                                                                                                                                                                         
  File "/Users/adefusco/Applications/miniconda3/envs/dc_tests/lib/python3.6/unittest/case.py", line 605, in run                                     
    testMethod()                                                    
  File "/Users/adefusco/Applications/miniconda3/envs/dc_tests/lib/python3.6/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)                                                                                           
  File "<string>", line 2, in test_values    
AttributeError: 'list' object has no attribute 'dtype'    
```

## Incorrect failure mode with generators
In many cases I want to write a separate test for every value in the array. I can use a generator to yield multiple test functions.

Notice here that the same `ints.dtype` line should have caused a single AttributeError. Instead ipython_nose itself fails. This leads to problems on the DataCamp platform in that the entire `Check Project` fails and no test output is presented to the test taker.

```python
In [6]: %%nose                                   
   ...: def test_values():                                                           
   ...:     d = ints.dtype                           
   ...:     def _test_value(v):                                                                              
   ...:         assert v > 5, '{} is not greater than 5'.format(v)
   ...:     for i in ints:                                                                                                                                                        
   ...:         yield _test_value, v
   ...:                                                          
--------------------------------------------------------------------------- 
AttributeError                            Traceback (most recent call last)
<ipython-input-6-dad9faa5d820> in <module>()                                                                                                             
----> 1 get_ipython().run_cell_magic('nose', '', "def test_values():\n    d = ints.dtype\n    def _test_value(v):\n        assert v > 5, '{} is not greater than 5'.format(v)\n   
 for i in ints:\n        yield _test_value, v")                                                                            
                                                                                                                                                                                  
~/Applications/miniconda3/envs/dc_tests/lib/python3.6/site-packages/IPython/core/interactiveshell.py in run_cell_magic(self, magic_name, line, cell)
   2129             magic_arg_s = self.var_expand(line, stack_depth)
   2130             with self.builtin_trap:                                                                                  
-> 2131                 result = fn(magic_arg_s, cell)                                                             
   2132             return result            
   2133                                                                                                                
                                                                                                
~/Applications/miniconda3/envs/dc_tests/lib/python3.6/site-packages/ipython_nose.py in nose(line, cell, test_module)
    303                                                                                                        
    304     nose_core.TestProgram(               
--> 305         argv=argv, suite=tests, addplugins=[plug], exit=False, config=config)
    306                                              
    307     ## for debugging      
   307     ## for debugging                                                                                                                                              [23/143]
                                                                           
~/Applications/miniconda3/envs/dc_tests/lib/python3.6/site-packages/nose/core.py in __init__(self, module, defaultTest, argv, testRunner, testLoader, env, config, suite, exit, pl
ugins, addplugins)                  
    119             self, module=module, defaultTest=defaultTest,
    120             argv=argv, testRunner=testRunner, testLoader=testLoader,
--> 121             **extra_args)                                          
    122                                     
    123     def getAllConfigFiles(self, env=None):                                                                                                                                
                                                                                                                           
~/Applications/miniconda3/envs/dc_tests/lib/python3.6/unittest/main.py in __init__(self, module, defaultTest, argv, testRunner, testLoader, exit, verbosity, failfast, catchbreak,
 buffer, warnings, tb_locals)                                                                                                                       
     93         self.progName = os.path.basename(argv[0])           
     94         self.parseArgs(argv)                                                                                         
---> 95         self.runTests()                       
     96                                  
     97     def usageExit(self, msg=None):                                                                             
                                                        
~/Applications/miniconda3/envs/dc_tests/lib/python3.6/site-packages/nose/core.py in runTests(self)                  
    205         if plug_runner is not None:  
    206             self.testRunner = plug_runner
--> 207         result = self.testRunner.run(self.test)                              
    208         self.success = result.wasSuccessful()
    209         if self.exit:                                                                                
                                                                  
~/Applications/miniconda3/envs/dc_tests/lib/python3.6/site-packages/nose/core.py in run(self, test)                                                                               
     66         result.printErrors()
     67         result.printSummary(start, stop)                 
---> 68         self.config.plugins.finalize(result)                        
     69         return result                                              
     70                                                                                                                                                  
                                                                                                                                                                                  
~/Applications/miniconda3/envs/dc_tests/lib/python3.6/site-packages/nose/plugins/manager.py in __call__(self, *arg, **kw)  
     97                                                                                                                                                                           
     98     def __call__(self, *arg, **kw):                                                                                                         
---> 99         return self.call(*arg, **kw)                        
    100                                                                                                                      
    101     def addPlugin(self, plugin, call):                                                                     
                                             
~/Applications/miniconda3/envs/dc_tests/lib/python3.6/site-packages/nose/plugins/manager.py in simple(self, *arg, **kw)
    165         """                                                                             
    166         for p, meth in self.plugins:                                                                        
--> 167             result = meth(*arg, **kw)                                                                  
    168             if result is not None:       
    169                 return result                                         
                                                     
~/Applications/miniconda3/envs/dc_tests/lib/python3.6/site-packages/ipython_nose.py in finalize(self, result)
    186                 result.wasSuccessful(),                   
    187                 self.num_tests, self.n_failures, self.n_errors,                                                                                                           
--> 188                 self.tests) 
    189                                                          
    190     def setOutputStream(self, stream):                              
                                                                           
~/Applications/miniconda3/envs/dc_tests/lib/python3.6/site-packages/ipython_nose.py in finalize(self, pass_or_fail, n_tests, n_failures, n_errors, tests)
     58                    "errors":   n_errors      # The number of tests that errored out, which mean it couldn't run but dind'                                                 
     59                    },                                                                                              
---> 60                "tests": list(map(self._dump_test, tests))                                                                                                                 
     61                }                                                                                                                            
     62                                                             
                                                                                                                             
~/Applications/miniconda3/envs/dc_tests/lib/python3.6/site-packages/ipython_nose.py in _dump_test(self, test_tuple)
     73     def _dump_test(self, test_tuple):
     74         test, exc, res  = test_tuple                                                                           
---> 75         return { "name": str(test.test.test.__name__), # NoseTest.SomeTestCaseClass.func
     76                  "success": res == "success",                                                               
     77                  "message": ''.join(traceback.format_exception(*exc)[-1:]) if res != "success" else ""}
                                                 
AttributeError: 'Failure' object has no attribute 'test'     
```

### expected output
Using the original fork of ipython_nose I get the following result. Notice that here nose indicates that one test was run.

```python
In [1]: %load_ext ipython_nose

In [2]: import numpy as np

In [3]: ints = np.random.randint(0, 10, size=5).tolist()

In [4]: ints
Out[4]: [2, 9, 4, 0, 6]

In [5]: %%nose
   ...: def test_values():
   ...:     d = ints.dtype
   ...:     def _test_value(v):
   ...:         assert v > 5, '{} is not greater than 5'.format(v)
   ...:     for i in ints:
   ...:         yield _test_value, 5
   ...: 
Out[5]: 
0/1 tests passed; 1 failed
========
Failure: AttributeError ('list' object has no attribute 'dtype')
========
Traceback (most recent call last):
  File "/Users/adefusco/Applications/miniconda3/envs/itests/lib/python3.6/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/Users/adefusco/Applications/miniconda3/envs/itests/lib/python3.6/unittest/case.py", line 605, in run
    testMethod()
  File "/Users/adefusco/Applications/miniconda3/envs/itests/lib/python3.6/site-packages/nose/failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "/Users/adefusco/Applications/miniconda3/envs/itests/lib/python3.6/site-packages/nose/loader.py", line 251, in generate
    for test in g():
  File "<string>", line 2, in test_values
AttributeError: 'list' object has no attribute 'dtype'
```

### if the student did the exercise correctly
Using **either** the original repo or the datacamp fork 5 tests are run everything works correctly.

```python
In [1]: %load_ext ipython_nose                                                                                           
         
In [2]: import numpy as np                                                                                   
                
In [3]: ints = np.random.randint(0, 10, size=5)                                                                              
                                                                                                                         
In [4]: ints                                                                                                                  
Out[4]: array([7, 7, 2, 0, 0]) 

In [6]: %%nose                                                     
   ...: def test_values():
   ...:     d = ints.dtype          
   ...:     def _test_value(v):
   ...:         assert v > 5, '{} is not greater than 5.'.format(v)
   ...:     for i in ints:                                                                                               
   ...:         yield _test_value, i
   ...:                                                                                                      
   ...:         
Out[6]:                                                                                                                    
2/5 tests passed; 3 failed                                                                                               
========                                 
__main__.test_values(2,)                                                                                     
========        
Traceback (most recent call last):                                                                                           
  File "/Users/adefusco/Applications/miniconda3/envs/itests/lib/python3.6/unittest/case.py", line 59, in testPartExecutor
    yield                                                                                                                     
  File "/Users/adefusco/Applications/miniconda3/envs/itests/lib/python3.6/unittest/case.py", line 605, in run
    testMethod()                                                                                                         
  File "/Users/adefusco/Applications/miniconda3/envs/itests/lib/python3.6/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)                                                                                     
  File "<string>", line 4, in _test_value
AssertionError: 2 is not greater than 5. 

========                  
__main__.test_values(0,)            
========                       
Traceback (most recent call last):                                 
  File "/Users/adefusco/Applications/miniconda3/envs/itests/lib/python3.6/unittest/case.py", line 59, in testPartExecutor
    yield                           
  File "/Users/adefusco/Applications/miniconda3/envs/itests/lib/python3.6/unittest/case.py", line 605, in run
    testMethod()
  File "/Users/adefusco/Applications/miniconda3/envs/itests/lib/python3.6/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)                                                                                                 
  File "<string>", line 4, in _test_value
AssertionError: 0 is not greater than 5.                                                                     
                
========                                                                                                                     
__main__.test_values(0,)                                                                                                 
========                                                                                                                      
Traceback (most recent call last):                                                                           
  File "/Users/adefusco/Applications/miniconda3/envs/itests/lib/python3.6/unittest/case.py", line 59, in testPartExecutor
    yield                                                                                                                  
  File "/Users/adefusco/Applications/miniconda3/envs/itests/lib/python3.6/unittest/case.py", line 605, in run
    testMethod()                         
  File "/Users/adefusco/Applications/miniconda3/envs/itests/lib/python3.6/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "<string>", line 4, in _test_value
AssertionError: 0 is not greater than 5.
```

**Comment by machow** [comment]
@AlbertDeFusco thanks for raising this case. I think I've found the line where the original ipython_nose handles these cases so will try to resolve today

https://github.com/datacamp/ipython_nose/blob/8ed0ddc9867c174557ba0e09140d362236544ee6/ipython_nose.py#L265

**Comment by machow** [comment]
@AlbertDeFusco I released a change under v0.4.1, but have only tested locally, since there seemed to be an unrelated issue with Teach builds. @rv2e and DataCamp's learn engineering team will take over the maintenance of this repo, and will handle putting it in a project image. You should be able to install it in the `requirements.sh` using

```
pip3 install git+https://github.com/datacamp/ipython_nose.git@v0.4.1
```

Let me know if it doesn't fix the issues and I can take another look at it!

**Comment by AlbertDeFusco** [comment]
I can confirm that 0.4.1 fixes the issue.

Here's the state of my understanding of nose and ipython_nose. This notebook could be turned into tests of this project. The last two `no tests found??` section is where things can get interesting.

https://github.com/AlbertDeFusco/ipython_nose/blob/master/examples/testing.ipynb
